version: 2
updates:
  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: "chore(deps)"
      include: scope
    groups:
      dart-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    labels:
      - ci
      - dependencies
    commit-message:
      prefix: "chore(ci)"
